### ISSUE TITLE
defaul bufferSize should be 0

### ISSUE THREAD

**Issue by DmitrySane** [spectrum-project/konveyor#21]
I want to split zip archive into entry. Got the output:
CONSUMERS: 1
entry_1.txt
entry_2.txt
CONSUMERS: 1
entry_3.txt

But the output should be:
CONSUMERS: 1
entry_1.txt
CONSUMERS: 1
entry_2.txt
CONSUMERS: 1
entry_3.txt

Work if set the bufferSize = 0

**Comment by svok** [comment]
Fixed
